### PR TITLE
WIP Code cleanup

### PR DESCRIPTION
**Pull request by Odisseuss**
I'll just create the pull request now, but i will keep working on it.

### CODE REVIEW

**Comment by jeffalo** [comment]
I know it's WIP, but this is great work! I am so sorry about all of the variables which were practically me slamming my hands on the keyboard. 
You've managed to rename practically every variable, and the code is readable! Thanks so much!!

**Comment by jeffalo** [comment]
@Odisseuss Not to rush or anything, but how's the code cleanup coming along? I'm a bit worried to make my own changes, for git conflict reasons.

**Comment by Odisseuss** [comment]
@JeffaloBob I am sorry for not working anymore but something intervened and i am quite busy untill Friday next week. If you want either you can make some more changes on this branch, or merge the pull request now and i will retake the issue next Friday. Sorry for the inconvenience

**Comment by jeffalo** [comment]
@Odisseuss don't worry, about it. :)

im also quite busy with school and stuff.

**Comment by Odisseuss** [comment]
@JeffaloBob I freed my schedule up a bit for monday so i can work then..

**Comment by jeffalo** [comment]
@Odisseuss hey, look this is just a small open source project, you should do whatever else you have to do first, and once you have free time and you're willing, then work on this.

**Comment by Odisseuss** [comment]
@JeffaloBob Oh yeah, definetely. It just happened that my schedule freed up a bit on Monday

**Comment by Odisseuss** [comment]
@JeffaloBob  Ok so for now i can't outsource more functions to different files, but i think this made the yeeter.js file a lot more slim. I can't put all functions in the other files though as they depend on some global variables. If you have any suggestions please let me know.

**Comment by jeffalo** [comment]
@Odisseuss Wow! Just looking at it, it's so much slimmer and readable. Is it currently in a mergeable state?

**Comment by Odisseuss** [comment]
@JeffaloBob Yep, i tested and everything worked ok, but please double check maybe i missed something

**Comment by jeffalo** [comment]
@Odisseuss I did a fairly quick test, and it seems like it's perfect 😃 thank you so much for your help, i'll merge the pull request now,

**Comment by JeffaloBob** [comment]
@Odisseuss I was looking back at your improvements, I had a question. How do all the separated files interact? Is it through the module script near the end of each file? How does that work? I'm new to node js, so I don't really understand.

Thanks in advance. 😃😃

**Pull request merged**
