### PR TITLE
Update variables and variable names, Remove redundant code

### PR DESCRIPTION
**Pull request by Odisseuss**
I renamed the html elements id's to keep a certain naming style. Also gave more meaningful names to variables from the yeeter.js file. Lastly, i removed some redundant pieces of code, and refactored it a bit. Please leave me a comment with your feedback.

### CODE REVIEW

**Comment by jeffalo** [comment]
Thanks for the help, but when I try merging the changes it seems to have to have some kind of conflict. I'm new to this what does it mean?

**Comment by Odisseuss** [comment]
So, what happened is that you commited some changes while i was working on my own branch for this issue. The fact that we both edited the same files and the same sections in them is a conflict. This means that git doesn't know which changes to keep so you have to solve the conflicts manually, deciding which changes to keep and which to delete. It's nothing bad, but please try to commit often so that i can pull the changes and avoid conflicts in the future

**Comment by Odisseuss** [comment]
Ok i fixed the conflicts, but just to be sure test the app out to make sure that everything works as normal. I will take a look as well when i get home. Also, i will start working on the bot name issue.

**Comment by jeffalo** [comment]
Thanks! I'll be sure to test.

**Comment by jeffalo** [comment]
There were a couple of issues.

When I tried to make all of the bots leave I got an error Uncaught (in promise) TypeError: client.leave is not a function
    at HTMLButtonElement.leave (yeeter.js:42)

and when pressing the yeet button I got an error about lateststatus is not defined, but I just had to change that in the function back to update for it to work.

I unmerged the changes. But still thanks for the help

@Odisseuss

**Comment by Odisseuss** [comment]
Oh.. you shouldn't have reverted everything, but that's ok

**Comment by jeffalo** [comment]
Oops, sorry. I'm new to this so I'm not really sure how I'm supposed to do things. How should we proceed?

**Pull request merged**
