### PR TITLE
WIP Add smart bot naming

### PR DESCRIPTION
**Pull request by Odisseuss**
@JeffaloBob 
Ok, so i mostly implemented everything there was. There is one thing though: If the amount of bots specified in the todoForm is bigger than the length of the list of names provided in the advanced settings, what should happen? Should it loop through them again? Or limit the bot amount to that of the list of names' length?

P.S. Someone needs to clean the code as it is getting pretty messy with all the global variables, their names, and the ones that are not used/ redundantly used

### CODE REVIEW

**Comment by jeffalo** [comment]
@Odisseuss looks good, I'll test it as soon as I can!

About the bot names vs the specified amount.

I think that once the specified bot names option is chosen, the amount value on the form should become how many times the specified names should join 

Sorry, if that's confusing then here's and example.

There are 5 names on the specified name list.

eg.
John
Timmy
Smith
Luke
Henry

If the option to use that list is chosen, then if the amount value is 1, then all of those bots join, if it's 2 then they would join as [specified name]+[number]

eg.
John2

Hopefully that makes sense.

Thank you so much for your help, I'll clean up the code a bit once this feature is finished. :)

**Comment by jeffalo** [comment]
@Odisseuss Just tested it out.

It works! Thanks so much.

Some bugs I noticed:

### When the [number]+[suffix] option is chosen, the bots join with a prefix and a suffix:
image

### When the [prefix]+[number] option is chosen, the bots join with a duplicated number:
image

### Other:

I was thinking, maybe for when a user selects the specified name list option (at least for the first ones) they wouldn't have a number at the end of their name.

Right now they join as:

John1
Timmy2
Smith3
Luke4
Henry5

and I was thinking, for the first of each, they should join as
John
Timmy
Smith
Luke
Henry

and then for the next set that join (eg. if the user selects 2 bots)
John2
Timmy2
Smith2
Luke2
Henry2

and so on and so forth.

### UX/UI:

Don't worry so much for these, (I probably can do them)

When the user opens the advanced settings menu, it's hard to tell if it's actually open, so maybe it could automatically scroll the user down?

When the user selects save, it probably should also do the same to the top of the page.

And the last one (super minor):

When you first open advanced settings, none of the radio buttons are selected, maybe it could already have [prefix]+[number] filled in since it's the default?

### Console:

This one is also pretty small, the console displays the names of the bots differently how they actually join.



But this feature, otherwise is pretty awesome! Thank you so much for your help, I won't merge this yet, but I will once it;s finished :)

**Comment by Odisseuss** [comment]
@JeffaloBob Oh, i have just seen your review. I managed to implement what you asked me for when the user chooses list naming option. It works as you asked now. Regarding the review you left, i did the exact same tests and they came out ok now. I will try testing in an actual Kahoot game just to make sure.

EDIT: It seems that when joining an actual Kahoot game, the bots join with the names following the pattern described above by you

**Comment by Odisseuss** [comment]
And yes, please wait untill everything is ok to merge. Just so that you avoid bugs in the master branch.

**Comment by Odisseuss** [comment]
@JeffaloBob I identified the issue in the code that caused the problem. I tested it myself in a Kahoot game and it all seems to be allright. Please test it yourself to double-check and then i think it it ok to merge.

**Comment by jeffalo** [comment]
Alright, thanks so much for your help @Odisseuss Really means a lot to me :)

**Comment by Odisseuss** [comment]
@JeffaloBob No worries, i really enjoy coding, always happy to help. I want to help with some other issues as well if that's ok

**Comment by jeffalo** [comment]
@Odisseuss You can help with any issue you want :)

I tested out your changes, it works like a charm except for 1 thing.

When I set the number of bots to 1, while using the name list with my 5 example names, I got 1 bot
Set to 2, I got 2 bots
3, I got 3 bots
4, 4 bots
5, I got 25 bots.
10, I got 50

When I first saw this I thought it was a bug, I think I know where you were going with this. I think the only bug would be the fact that 5 should give 5 bots (all of the bots on the list)

I think this is a simple less than/greater than or equal to issue, correct? I'm not sure so I'll wait for this to be sorted for the merge.

Again, thanks so much for the interest and help in my project.

**Comment by jeffalo** [comment]
@Odisseuss I'll transfer the UX/UI part of my review to a new issue.

**Comment by Odisseuss** [comment]
@JeffaloBob Okay, i identified and fixed the issue. So let me check things one more time.
When using the name list with let's say 5 names inserted. If the user inputs 1 in the "number of bots" field, then the result should be:
[name1]
[name2],
[name3],
[name4],
[name5]

But if the user inputs the number 2 in the field, then there should be 2*5  bots right?
This is what i understood from what you said in a post above:
image

**Comment by jeffalo** [comment]
@Odisseuss You got it! I think it's ready to merge now, what do you think?

**Comment by Odisseuss** [comment]
Yes, let me commit

EDIT: Done

**Comment by jeffalo** [comment]
Alright

**Comment by jeffalo** [comment]
@Odisseuss I have tested it and I'm going to merge it.

**Pull request merged**
